=== uestczw/emptyframe/src/main/resources/param-rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- 元素定义 -->
	<xs:element name="reg" type="xs:string" />
	<xs:element name="desc" type="xs:string" />
	<xs:element name="errMsg" type="xs:string" />
	<xs:element name="author" type="xs:string" />
	<xs:element name="address" type="xs:string" />

	<xs:attribute name="isreg" type="xs:boolean" />
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="ref" type="xs:QName" />
	<xs:attribute name="id" type="xs:ID" />

	<xs:attribute name="file" type="xs:anyURI" />
	<xs:element name="include">
		<xs:complexType mixed="true">
			<xs:attribute ref="file" />
		</xs:complexType>
	</xs:element>

	<!-- 根节点 -->
	<xs:element name="urls">
		<xs:complexType>
			<xs:sequence>
				<!-- 正则定义 -->
				<xs:element ref="regex" minOccurs="0" maxOccurs="999999" />
				<!-- params定义 -->
				<xs:element name="param1" minOccurs="0"
					maxOccurs="999999">
					<xs:complexType mixed="true">
						<xs:sequence>
							<xs:element ref="name" minOccurs="0" />
							<xs:element ref="required" minOccurs="0" />
							<xs:element ref="requiredMsg" minOccurs="0" />
							<xs:element ref="rule" minOccurs="0" />
							<xs:element ref="errMsg" minOccurs="0" />
							<xs:element ref="desc" minOccurs="0" />
						</xs:sequence>

						<xs:attribute ref="id" use="required" />
						<xs:attribute ref="name" use="required" />
						<xs:attribute ref="ref" />
					</xs:complexType>
				</xs:element>
				<!-- 路径映射 -->
				<xs:element ref="url" minOccurs="0" maxOccurs="999999" />
				<!-- 文件引用 -->
				<xs:element ref="include" minOccurs="0"
					maxOccurs="999999" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="regex">
		<xs:complexType>
			<xs:sequence>
				<!-- 正则 -->
				<xs:element ref="reg" />
				<!-- 错误消息 -->
				<xs:element ref="errMsg" />
				<!-- 正则描述 -->
				<xs:element ref="desc" />
			</xs:sequence>
			<xs:attribute ref="id" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="url">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" />
				<xs:element ref="desc" />
				<xs:element ref="author" />
				<xs:element ref="params" />
			</xs:sequence>
			<xs:attribute ref="isreg" />
			<xs:attribute ref="name" />
		</xs:complexType>
	</xs:element>

	<xs:element name="rule">
		<xs:complexType mixed="true">
			<xs:attribute ref="ref" />
		</xs:complexType>
	</xs:element>

	<xs:element name="requiredMsg" type="xs:string" />
	<xs:element name="required" type="xs:boolean"
		default="false" />
	<xs:element name="params">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" minOccurs="0" maxOccurs="99999" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="param">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="name" minOccurs="0" />
				<xs:element ref="required" minOccurs="0" />
				<xs:element ref="requiredMsg" minOccurs="0" />
				<xs:element ref="rule" minOccurs="0" />
				<xs:element ref="errMsg" minOccurs="0" />
				<xs:element ref="desc" minOccurs="0" />
			</xs:sequence>

			<xs:attribute ref="id" />
			<xs:attribute ref="name" />
			<xs:attribute ref="ref" />
		</xs:complexType>
	</xs:element>

	<xs:element name="name">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute ref="isreg" default="false" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uestczw/emptyframe/src/main/resources/param-rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<urls xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="param-rule.xsd">
	<!-- 通用正则配置 -->
	<regex id="reg_ip">
		<reg>^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$</reg>
		<errMsg>请输入正确的IP地址</errMsg>
		<desc>IP验证</desc>
	</regex>
	<regex id="reg_mac">
		<reg>^(?!.*[ \:\-]{2,}.*$)(([a-fA-F0-9]{2}([a-fA-F0-9]{2}){5})||([a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5})||([a-fA-F0-9]{2}( [a-fA-F0-9]{2}){5})||([a-fA-F0-9]{2}(-[a-fA-F0-9]{2}){5}))$</reg>
		<errMsg>请输入正确的MAC地址</errMsg>
		<desc>mac地址验证</desc>
	</regex>
	<regex id="reg_positive_integer">
		<reg>^[1-9]+[0-9]{0,8}$</reg>
		<errMsg>非法参数</errMsg>
		<desc>正整数验证</desc>
	</regex>
	<regex id="reg_integer">
		<reg>^[0-9]{0,8}$</reg>
		<errMsg>非法参数</errMsg>
		<desc>正整数验证</desc>
	</regex>
	<regex id="reg_soft_port">
		<reg>^(([1-9]\d{0,3})|([1-5]\d{4})|(6[0-4]\d{3})|(65[0-4]\d{2})|(655[0-2]\d)|(6553[0-5]))$</reg>
		<errMsg>端口号应在1-65535之间</errMsg>
		<desc>软端口号验证</desc>
	</regex>
	<regex id="reg_physical_interface">
		<reg>^[\w]{0,10}$</reg>
		<errMsg>请输入正确的物理端口号</errMsg>
		<desc>物理端口验证</desc>
	</regex>

	<!-- 通用分页查询 -->
	<url isreg="true" name="reg_all_ajax_page">
		<address><![CDATA[^/([\w\-\_]+/)+list(\.json)?$]]></address>
		<desc>通用分页查询页数和行数验证</desc>
		<author>张伟</author>
		<params>
			<param>
				<name>page</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule ref="reg_positive_integer" />
				<errMsg>当前页数输入错误</errMsg>
				<desc>查询页数</desc>
			</param>
			<param>
				<name>rows</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule ref="reg_positive_integer" />
				<errMsg>查询行数输入错误</errMsg>
				<desc>查询行数</desc>
			</param>
			<param>
				<name>keywords</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule>^.*$</rule>
				<errMsg>关键词错误</errMsg>
				<desc>关键词</desc>
			</param>
			<param>
				<name>status</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule>^.*$</rule>
				<errMsg>状态错误</errMsg>
				<desc>状态错误</desc>
			</param>
		</params>
	</url>

	<!-- 通用接口,此处是为了能够接受参数 -->
	<url isreg="true" name="reg_all_api">
		<address><![CDATA[^/api/.*\.(json|do)$]]></address>
		<desc>通用分页查询页数和行数验证</desc>
		<author>张伟</author>
		<params>
			<param>
				<name>data</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule></rule>
				<errMsg>当前页数输入错误</errMsg>
				<desc>查询页数</desc>
			</param>
			<param>
				<name>sign</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule></rule>
				<errMsg>查询行数输入错误</errMsg>
				<desc>查询行数</desc>
			</param>
		</params>
	</url>

	<url isreg='true'>
		<address><![CDATA[^(/upImg|/(admin|app|staff)/loadImg|/(admin|app|staff)/image|/(admin|app|staff)/load_img)\.(json|do)$]]></address>
		<desc>图片上传下载</desc>
		<author>张伟</author>
		<params>
			<param>
				<name>file</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule></rule>
				<errMsg></errMsg>
				<desc>上传文件</desc>
			</param>
			<param>
				<name>path</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule></rule>
				<errMsg></errMsg>
				<desc>加载图片路径</desc>
			</param>
		</params>
	</url>
	<url name="error">
		<address>/error.do</address>
		<desc>http请求统一错误封装</desc>
		<author>张伟</author>
		<params>
			<param>
				<name>msg</name>
				<required>false</required>
				<requiredMsg></requiredMsg>
				<rule></rule>
				<errMsg></errMsg>
				<desc>错误提示信息</desc>
			</param>
		</params>
	</url>
</urls>
